### ISSUE TITLE
Graph badly generated

### ISSUE THREAD

**Issue by SamyCookie** [habnabit/twisted-depgraph#1]
Regression since fde548bb59db8ab6964b6a83a97a3d02a8b2f3cd.
*.__init__ modules are badly detected (detected twice).

**Comment by habnabit** [comment]
Oh yikes. I'll take a look

**Comment by SamyCookie** [comment]
Thanks :)

**Comment by habnabit** [comment]
Should be fixed in 2f381b5296abed7cdf561edceb07f9734331c289.

**Comment by SamyCookie** [comment]
Confirmed as fixed. Thanks again for fixing this quickly !
